export const labels=
    [
        "Company Name",
        "Company Type",
        "Company Category",
        "First Name",
        "Middle Name",
        "Last Name",
        "Email",
        "Alternate Email",
        "Mobile Prefix",
        "Mobile Number",
        "Alternate Mobile Number",
        "Country",
        "Country Label",
        "Country Code",
        "State",
        "State Code",
        "Address Line 1",
        "Address Line 2",
        "City",
        "Division/Taluk",
        "Village/Area/Ward/Block",
        "Zip/Pin Code",
        "CIN No",
        "GST No",
        "PAN No",
        "TAN No",
        "Trade Name or Trade No",
        "Factory Licence No",
      ];
